import turtle
turtle.screensize(None,None,"blue")
turtle.shape("turtle")
turtle.fillcolor("yellow")
turtle.begin_fill()
turtle.forward(100)
turtle.left(144)
turtle.forward(100)
turtle.left(144)
turtle.forward(100)
turtle.left(144)
turtle.forward(100)
turtle.left(144)
turtle.forward(100)
turtle.end_fill()
